<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <UseWPF>true</UseWPF>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>PointlessWaymarksMetadataDisplayIcon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="PointlessWaymarks.CommonTools.BuildDateAttribute">
            <_Parameter1>$([System.DateTime]::UtcNow.ToString("yyyyMMddHHmmss"))</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PointlessWaymarksTools\PointlessWaymarks.WpfCommon\PointlessWaymarks.WpfCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Jot" />
    </ItemGroup>

    <ItemGroup>
      <None Update="PointlessWaymarksMetadataDisplayIcon.bmp">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="MetadataDisplayInstallerLeftImage.bmp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="MetadataDisplayInstallerTopRightImage.bmp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <None Remove="MetadataDisplayIcon.ico" />
      <Resource Include="PointlessWaymarksMetadataDisplayIcon.ico">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
    </ItemGroup>

    <PropertyGroup>
        <Version>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</Version>
        <AssemblyVersion>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</AssemblyVersion>
        <FileVersion>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</FileVersion>
    </PropertyGroup>

</Project>
