<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <UseWPF>true</UseWPF>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>PointlessWaymarksSiteViewerIcon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="PointlessWaymarks.CommonTools.BuildDateAttribute">
            <_Parameter1>$([System.DateTime]::UtcNow.ToString("yyyyMMddHHmmss"))</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <PropertyGroup>
        
        <Version>$([System.DateTime]::UtcNow.ToString("yyyy.M.d.Hmm"))</Version>
        <AssemblyVersion>$([System.DateTime]::UtcNow.ToString("yyyy.M.d.Hmm"))</AssemblyVersion>
        <FileVersion>$([System.DateTime]::UtcNow.ToString("yyyy.M.d.Hmm"))</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="PointlessWaymarksSiteViewerIcon.ico" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommandLineParser" />
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="Dragablz" />
        <PackageReference Include="Jot" />
        <PackageReference Include="Metalama.Framework" />
        <PackageReference Include="Microsoft.Web.WebView2" />
        <PackageReference Include="Microsoft.Web.WebView2.DevToolsProtocolExtension" />
        <PackageReference Include="ModernWpfUI" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PointlessWaymarks.CmsWpfControls\PointlessWaymarks.CmsWpfControls.csproj" />
        <ProjectReference Include="..\PointlessWaymarksTools\PointlessWaymarks.WpfCommon\PointlessWaymarks.WpfCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="PointlessWaymarksSiteViewerIcon.ico">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Resource>
    </ItemGroup>

    <ItemGroup>
      <None Update="SiteViewerInstallerLeftImage.bmp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="SiteViewerInstallerTopRightImage.bmp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>