// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PointlessWaymarks.CmsData.ContentHtml.ContentGalleryHtml
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using PointlessWaymarks.CmsData.CommonHtml;
    using PointlessWaymarks.CommonTools;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class ContentGalleryPage : ContentGalleryPageBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n\n");
            this.Write("\n");
            this.Write("\n<!DOCTYPE html>\n<html lang=\"en\">\n<head data-generationversion=\"");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationVersion?.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffff") ?? string.Empty));
            
            #line default
            #line hidden
            this.Write("\">\n    <meta charset=\"utf-8\" lang=\"");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LangAttribute));
            
            #line default
            #line hidden
            this.Write("\" dir=\"");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DirAttribute));
            
            #line default
            #line hidden
            this.Write("\">\n    <title>");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SiteName.HtmlEncode()));
            
            #line default
            #line hidden
            this.Write(" - Photographs</title>\n    <meta name=\"description\" content=\"All photographs on ");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SiteName.HtmlEncode()));
            
            #line default
            #line hidden
            this.Write(" listed by date.\">\n    <meta name=\"author\" content=\"");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreatedBy.HtmlEncode()));
            
            #line default
            #line hidden
            this.Write("\">\n    <meta name=\"keywords\" content=\"photographs, camera roll\" >\n\n    <meta prop" +
                    "erty=\"og:site_name\" content=\"");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SiteName.HtmlEncode()));
            
            #line default
            #line hidden
            this.Write("\" />\n    <meta property=\"og:url\" content=\"https:");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PageUrl ?? string.Empty));
            
            #line default
            #line hidden
            this.Write("\" />\n    <meta property=\"og:type\" content=\"article\" />\n    <meta property=\"og:tit" +
                    "le\" content=\"Photographs By Date\" />\n    <meta property=\"og:description\" content" +
                    "=\"All photographs on ");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SiteName.HtmlEncode()));
            
            #line default
            #line hidden
            this.Write(" listed by date.\" />\n\n    ");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Tags.OpenGraphImageMetaTags(MainImage)));
            
            #line default
            #line hidden
            this.Write("\n\n    <link rel = \"schema.DC\" href = \"http://purl.org/DC/elements/1.0/\">\n    <met" +
                    "a name=\"DC.Title\" content=\"Photographs By Date\">\n    <meta name=\"DC.Creator\" con" +
                    "tent=\"");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreatedBy.HtmlEncode()));
            
            #line default
            #line hidden
            this.Write("\">\n    <meta name=\"DC.Publisher\" content=\"");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SiteName.HtmlEncode()));
            
            #line default
            #line hidden
            this.Write("\">\n    <meta name=\"DC.Description\" content=\"All photographs on ");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SiteName.HtmlEncode()));
            
            #line default
            #line hidden
            this.Write(" listed by date.\">\n    <meta name=\"DC.Date\" content=\"");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LastDateGroupDateTime?.ToString("yyyy-MM-dd").HtmlEncode() ?? string.Empty));
            
            #line default
            #line hidden
            this.Write("\">\n    <meta name=\"DC.Format\" content=\"text/html\">\n    <meta name=\"DC.Language\" c" +
                    "ontent=\"en-US\">\n\n    <link rel=\"alternate\" type=\"application/rss+xml\" \n      tit" +
                    "le=\"");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture($"RSS Feed for {UserSettingsSingleton.CurrentSettings().SiteName} - Photos".HtmlEncode()));
            
            #line default
            #line hidden
            this.Write("\"\n      href=\"");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UserSettingsSingleton.CurrentSettings().PhotosRssUrl()));
            
            #line default
            #line hidden
            this.Write("\" />\n\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n" +
                    "\n    ");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Tags.CssStyleFileString()));
            
            #line default
            #line hidden
            this.Write("\n    ");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Tags.FavIconFileString()));
            
            #line default
            #line hidden
            this.Write("\n\n    <script src=\"");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UserSettingsSingleton.CurrentSettings().SiteResourcesUrl()));
            
            #line default
            #line hidden
            this.Write("gsap.min.js\"></script>\n    <script src=\"");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UserSettingsUtilities.ContentGalleryJavascriptUrl()));
            
            #line default
            #line hidden
            this.Write("\"></script>\n\n</head>\n\n<body>\n    ");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Tags.StandardHeader().Result.ToString()));
            
            #line default
            #line hidden
            this.Write("\n    ");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HorizontalRule.StandardRule()));
            
            #line default
            #line hidden
            this.Write("\n    ");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Tags.TitleDiv($"{SiteName} - Contents").ToString()));
            
            #line default
            #line hidden
            this.Write("\n    <div class=\"search-input-container enable-after-loading wait-cursor\">\n      " +
                    "  <input type=\"text\" class=\"search-input\" id=\"userSearchText\" onkeyup=\"searchCon" +
                    "tent()\" placeholder=\"Search Content...\" autocomplete=\"off\">\n    </div>\n    ");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ItemContentTag?.ToString() ?? string.Empty));
            
            #line default
            #line hidden
            this.Write("\n    ");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HorizontalRule.StandardRule()));
            
            #line default
            #line hidden
            this.Write("\n    ");
            
            #line 1 "E:\Code\pwp-03\PointlessWaymarks.CmsData\ContentHtml\ContentGalleryHtml\ContentGalleryPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Footer.StandardFooterDiv().Result));
            
            #line default
            #line hidden
            this.Write("\n</body>\n\n</html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class ContentGalleryPageBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
