<Project>
  <PropertyGroup>
    <Version>$(LiveChartsVersion)</Version>
    <Authors>$(LiveChartsAuthors)</Authors>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/beto-rodriguez/LiveCharts2</RepositoryUrl>

    <!-- Deterministic build -->
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>

    <!-- Symbol package format -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <!-- Custom output folder -->
    <PackageOutputPath>$(SolutionDir)nukpg</PackageOutputPath>

    <IsPackable>true</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>

    <Description>Simple, stunning, interactive and powerful data visualization for .Net.</Description>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Other packing related properties... -->
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>bin/$(Configuration)/$(TargetFramework)/$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(PathToPackAssets)icon.png" Pack="true" PackagePath="\" />
    <None Include="$(PathToPackAssets)README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
