<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <UseWPF>true</UseWPF>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>PointlessWaymarksPhotoMetadataBasicsIcon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="PointlessWaymarks.CommonTools.BuildDateAttribute">
            <_Parameter1>$([System.DateTime]::UtcNow.ToString("yyyyMMddHHmmss"))</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <PropertyGroup>
        <Version>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</Version>
        <AssemblyVersion>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</AssemblyVersion>
        <FileVersion>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="PointlessWaymarksPhotoMetadataBasicsIcon.ico" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Jot" Version="2.1.17" />
        <PackageReference Include="Metalama.Patterns.Observability" Version="2026.1.19" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PointlessWaymarks.FeatureIntersectionTags\PointlessWaymarks.FeatureIntersectionTags.csproj" />
        <ProjectReference Include="..\PointlessWaymarksTools\PointlessWaymarks.WpfCommon\PointlessWaymarks.WpfCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Resource Include="PointlessWaymarksPhotoMetadataBasicsIcon.ico">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
    </ItemGroup>

    <ItemGroup>
      <None Update="PhotoMetadataBasicsInstallerLeftImage.bmp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="PhotoMetadataBasicsInstallerTopRightImage.bmp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="README_PhotoMetadataBasicsGui.md">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>