<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyTitle>PressSharper.UnitTests</AssemblyTitle>
    <Product>PressSharper.UnitTests</Product>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Metalama.Framework" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PointlessWaymarks.PressSharper\PointlessWaymarks.PressSharper.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="PressSharper-UnitTests-License.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="README_PressSharper-UnitTests.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="README_UnitTests.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>