<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>PointlessWaymarksPowerShellRunnerIcon.ico</ApplicationIcon>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <MetalamaRoslynIsCompileTimeOnly>False</MetalamaRoslynIsCompileTimeOnly>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="PointlessWaymarksPowerShellRunnerIcon.ico" />
        <None Remove="PowerShellEditor\PowerShell.xshd" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="PointlessWaymarks.CommonTools.BuildDateAttribute">
            <_Parameter1>$([System.DateTime]::UtcNow.ToString("yyyyMMddHHmmss"))</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <PropertyGroup>
        
        <Version>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</Version>
        <AssemblyVersion>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</AssemblyVersion>
        <FileVersion>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="PowerShellEditor\PowerShell.xshd" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AvalonEdit" />
        <PackageReference Include="CronExpressionDescriptor" />
        <PackageReference Include="Cronos" />
        <PackageReference Include="DiffPlex.Wpf" />
        <PackageReference Include="FilterDataGrid" />
        <PackageReference Include="Jot" />
        <PackageReference Include="Metalama.Framework" />
        <PackageReference Include="Microsoft.Web.WebView2" />
        <PackageReference Include="ValueInjecter" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LiveCharts2\src\skiasharp\LiveChartsCore.SkiaSharp.WPF\LiveChartsCore.SkiaSharpView.WPF.csproj" />
        <ProjectReference Include="..\PointlessWaymarks.PowerShellRunnerData\PointlessWaymarks.PowerShellRunnerData.csproj" />
        <ProjectReference Include="..\PointlessWaymarksTools\PointlessWaymarks.VaultfuscationTools\PointlessWaymarks.VaultfuscationTools.csproj" />
        <ProjectReference Include="..\PointlessWaymarksTools\PointlessWaymarks.WpfCommon\PointlessWaymarks.WpfCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="PointlessWaymarksPowerShellRunnerIcon.ico">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Resource>
    </ItemGroup>

    <ItemGroup>
        <None Update="PowerShellRunnerInstallerTopRightImage.bmp">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="PowerShellRunnerLeftInstallerImage.bmp">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="README_PowershellRunnerGui.md">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>