<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>PointlessWaymarksPowerShellRunnerIcon.ico</ApplicationIcon>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <MetalamaRoslynIsCompileTimeOnly>False</MetalamaRoslynIsCompileTimeOnly>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="PointlessWaymarksPowerShellRunnerIcon.ico" />
        <None Remove="PowerShellEditor\PowerShell.xshd" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="PointlessWaymarks.CommonTools.BuildDateAttribute">
            <_Parameter1>$([System.DateTime]::UtcNow.ToString("yyyyMMddHHmmss"))</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <PropertyGroup>
        
        <Version>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</Version>
        <AssemblyVersion>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</AssemblyVersion>
        <FileVersion>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="PowerShellEditor\PowerShell.xshd" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
        <PackageReference Include="CronExpressionDescriptor" Version="2.45.0" />
        <PackageReference Include="Cronos" Version="0.13.0" />
        <PackageReference Include="DiffPlex.Wpf" Version="1.9.1" />
        <PackageReference Include="FilterDataGrid" Version="1.2.9" />
        <PackageReference Include="Jot" Version="2.1.17" />
        <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc5.4" />
        <PackageReference Include="Metalama.Framework" Version="2026.0.23" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
        <PackageReference Include="ValueInjecter" Version="3.2.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PointlessWaymarks.PowerShellRunnerData\PointlessWaymarks.PowerShellRunnerData.csproj" />
        <ProjectReference Include="..\PointlessWaymarksTools\PointlessWaymarks.VaultfuscationTools\PointlessWaymarks.VaultfuscationTools.csproj" />
        <ProjectReference Include="..\PointlessWaymarksTools\PointlessWaymarks.WpfCommon\PointlessWaymarks.WpfCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="PointlessWaymarksPowerShellRunnerIcon.ico">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Resource>
    </ItemGroup>

    <ItemGroup>
        <None Update="PowerShellRunnerInstallerTopRightImage.bmp">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="PowerShellRunnerLeftInstallerImage.bmp">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="README_PowershellRunnerGui.md">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>