<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ApplicationIcon>PointlessWaymarksCmsAutomationIcon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="PointlessWaymarksCmsAutomationIcon.ico" />
        <None Remove="README.md" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="HtmlAgilityPack" />
        <PackageReference Include="IdentityModel" />
        <PackageReference Include="Metalama.Framework" />
        <PackageReference Include="Mjml.Net" />
        <PackageReference Include="ObjectDumper.NET" />
    </ItemGroup>

    <ItemGroup>
        <None Update="MemoriesSmtpEmailFromWebSettingsSample.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="README_CmsTask-MemoriesEmail.md">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="PointlessWaymarks.CommonTools.BuildDateAttribute">
            <_Parameter1>$([System.DateTime]::UtcNow.ToString("yyyyMMddHHmmss"))</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <PropertyGroup>
        
        <Version>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</Version>
        <AssemblyVersion>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</AssemblyVersion>
        <FileVersion>$([System.DateTime]::Now.ToString("yyyy.M.d.Hmm"))</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Include="README.md">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PointlessWaymarksTools\PointlessWaymarks.VaultfuscationTools\PointlessWaymarks.VaultfuscationTools.csproj" />
        <ProjectReference Include="..\PointlessWaymarksTools\PointlessWaymarks.WindowsTools\PointlessWaymarks.WindowsTools.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="PointlessWaymarksCmsAutomationIcon.ico">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Resource>
    </ItemGroup>

</Project>