using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Input;
using Metalama.Patterns.Observability;
using WaterDaze.Models;
using WaterDaze.Services;

namespace WaterDaze.ViewModels;

[Observable]
public partial class YearFacetItemViewModel
{
    public List<MonthlyFlowRecord> MonthlyRecords { get; set; } = [];
    public int Year { get; set; }
}

[Observable]
public partial class MainViewModel
{
    private readonly GaugeAnalyticsService _analyticsService;
    private readonly IUsgsService _usgsService;
    private CancellationTokenSource? _cts;

    public MainViewModel(IUsgsService? usgsService = null, GaugeAnalyticsService? analyticsService = null)
    {
        _usgsService = usgsService ?? new UsgsService();
        _analyticsService = analyticsService ?? new GaugeAnalyticsService();

        AvailableSites = new ObservableCollection<GaugeSite>(GaugeSite.TucsonAreaSites);
        RefreshCommand = new RelayCommand(async () =>
        {
            if (SelectedSite != null) await LoadGaugeDataAsync(SelectedSite);
        });

        // Listen for SelectedSite changes generated by Metalama's [Observable]
        PropertyChanged += (sender, args) =>
        {
            if (args.PropertyName == nameof(SelectedSite) && SelectedSite != null)
            {
                _ = LoadGaugeDataAsync(SelectedSite);
            }
        };

        // Default select the first gauge (Rincon Creek -- 09485000)
        SelectedSite = AvailableSites.FirstOrDefault();
    }

    public ObservableCollection<GaugeSite> AvailableSites { get; }

    public ObservableCollection<MonthSummaryRecord> ClimatologySummaries { get; set; } = [];

    public GaugeDashboardData? DashboardData { get; private set; }

    public string ErrorMessage { get; set; } = string.Empty;

    public bool HasError { get; set; }

    public bool HasWarning { get; set; }

    public string WarningMessage { get; set; } = string.Empty;

    public string DataSourceSummary { get; set; } = string.Empty;

    public bool IsLoading { get; set; }

    public string LoadingStatus { get; set; } = string.Empty;

    public ObservableCollection<MonthlyFlowRecord> MonthlyRecords { get; set; } = [];

    public ICommand RefreshCommand { get; }

    public GaugeSite? SelectedSite { get; set; }

    public ObservableCollection<YearlyFlowRecord> TopDriestYears { get; } = [];
    public ObservableCollection<StreakRecord> TopDryStreaks { get; } = [];

    public ObservableCollection<DailyPeakFlowRecord> TopPeakFlowDays { get; } = [];

    public ObservableCollection<StreakRecord> TopWetStreaks { get; } = [];

    public ObservableCollection<YearlyFlowRecord> TopWettestYears { get; } = [];

    public ObservableCollection<YearFacetItemViewModel> YearFacets { get; } = [];

    public ObservableCollection<int> Years { get; set; } = [];

    public async Task LoadGaugeDataAsync(GaugeSite site)
    {
        if (_cts != null)
        {
            await _cts.CancelAsync();
        }
        _cts = new CancellationTokenSource();
        var token = _cts.Token;

        IsLoading = true;
        HasError = false;
        HasWarning = false;
        ErrorMessage = string.Empty;
        WarningMessage = string.Empty;
        LoadingStatus = $"Fetching streamflow records for {site.DisplayTitle}...";

        try
        {
            var processed = await _analyticsService.LoadAndProcessGaugeDataAsync(site, _usgsService, token);

            if (token.IsCancellationRequested) return;

            DashboardData = processed;
            HasWarning = processed.HasWarning;
            WarningMessage = processed.WarningMessage;
            DataSourceSummary = processed.DataSourceSummary;

            // Update UI Collections
            UpdateCollections(processed);

            LoadingStatus = string.Empty;
        }
        catch (OperationCanceledException)
        {
            // Operation canceled
        }
        catch (Exception ex)
        {
            HasError = true;
            ErrorMessage = $"Failed to load USGS streamflow data: {ex.Message}";
            DataSourceSummary = string.Empty;
        }
        finally
        {
            IsLoading = false;
        }
    }

    private void UpdateCollections(GaugeDashboardData data)
    {
        DataSourceSummary = data.DataSourceSummary;

        YearFacets.Clear();
        if (data is { Years: not null, MonthlyRecords: not null })
        {
            var grouped = data.MonthlyRecords.GroupBy(r => r.Year).ToDictionary(g => g.Key, g => g.ToList());
            foreach (var year in data.Years)
            {
                grouped.TryGetValue(year, out var months);
                YearFacets.Add(new YearFacetItemViewModel
                {
                    Year = year,
                    MonthlyRecords = months ?? []
                });
            }
        }

        ClimatologySummaries = new ObservableCollection<MonthSummaryRecord>(data.ClimatologySummaries);
        MonthlyRecords = new ObservableCollection<MonthlyFlowRecord>(data.MonthlyRecords ?? []);
        Years = new ObservableCollection<int>(data.Years ?? []);

        TopWetStreaks.Clear();
        foreach (var item in data.TopWetStreaks) TopWetStreaks.Add(item);

        TopDryStreaks.Clear();
        foreach (var item in data.TopDryStreaks) TopDryStreaks.Add(item);

        TopWettestYears.Clear();
        foreach (var item in data.TopWettestYears) TopWettestYears.Add(item);

        TopDriestYears.Clear();
        foreach (var item in data.TopDriestYears) TopDriestYears.Add(item);

        TopPeakFlowDays.Clear();
        foreach (var item in data.TopPeakFlowDays) TopPeakFlowDays.Add(item);
    }
}