<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultItems>false</EnableDefaultItems>
    <DefineSilverlight>true</DefineSilverlight>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Garmin.FIT.Sdk" Version="21.217.0" />
    <PackageReference Include="NetTopologySuite.IO.GPX" Version="1.1.1" />
    <PackageReference Include="OpenSilver" Version="3.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml">
      <Generator>MSBuild:Compile</Generator>
    </ApplicationDefinition>
    <Page Include="MainPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\StatsPanelControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\MapControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\PointsGridControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\ElevationChartControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\ActivityLogWindowControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\AboutWindowControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\BusyOverlayControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="obj\**;bin\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\SampleTrack.gpx" />
  </ItemGroup>

</Project>
