<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="NetVips" />
        <PackageReference Include="PDFtoImage" />
        <PackageReference Include="SkiaSharp" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\PointlessWaymarksTools\PointlessWaymarks.CommonTools\PointlessWaymarks.CommonTools.csproj" />
        <ProjectReference Include="..\PointlessWaymarksTools\PointlessWaymarks.WpfCommon\PointlessWaymarks.WpfCommon.csproj" />
    </ItemGroup>
</Project>